//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlaudiaPoliwka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biszkopt
    {
        public long idBiszkopt { get; set; }
        public Nullable<long> idRodzajBiszkoptu { get; set; }
        public Nullable<long> idPietra { get; set; }
    
        public virtual Pietra Pietra { get; set; }
        public virtual RodzajBiszkoptu RodzajBiszkoptu { get; set; }
    }
}
