//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlaudiaPoliwka
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiszkoptTortu
    {
        public long idBiszkopt { get; set; }
        public long idTorty { get; set; }
        public long idBiszkoptTortu { get; set; }
    }
}
