//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlaudiaPoliwka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostawa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dostawa()
        {
            this.Zamowienie = new HashSet<Zamowienie>();
        }
    
        public long idDostawa { get; set; }
        public System.DateTime DataOdbioru { get; set; }
        public Nullable<System.DateTime> GodzinaOdbioru { get; set; }
        public string NrTeleOdbiorcy { get; set; }
        public string Ulica { get; set; }
        public string KodPocztowy { get; set; }
        public string Miasto { get; set; }
        public string NrDomu { get; set; }
        public string NrMieszkania { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie> Zamowienie { get; set; }
    }
}
