//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlaudiaPoliwka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sweetEntities : DbContext
    {
        public sweetEntities()
            : base("name=sweetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoleClaims> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserTokens> AspNetUserTokens { get; set; }
        public virtual DbSet<Biszkopt> Biszkopt { get; set; }
        public virtual DbSet<BiszkoptTortu> BiszkoptTortu { get; set; }
        public virtual DbSet<Dostawa> Dostawa { get; set; }
        public virtual DbSet<DostawaDoKlienta> DostawaDoKlienta { get; set; }
        public virtual DbSet<DostawaDoPkt> DostawaDoPkt { get; set; }
        public virtual DbSet<FormaPlatnosci> FormaPlatnosci { get; set; }
        public virtual DbSet<FormaZaliczki> FormaZaliczki { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<KlientJopia> KlientJopia { get; set; }
        public virtual DbSet<Krem> Krem { get; set; }
        public virtual DbSet<KremTortu> KremTortu { get; set; }
        public virtual DbSet<Ksztalt> Ksztalt { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Logowanie> Logowanie { get; set; }
        public virtual DbSet<NazwaStylu> NazwaStylu { get; set; }
        public virtual DbSet<Pietra> Pietra { get; set; }
        public virtual DbSet<PietraTortu> PietraTortu { get; set; }
        public virtual DbSet<Platnosc> Platnosc { get; set; }
        public virtual DbSet<Praca> Praca { get; set; }
        public virtual DbSet<RodzajBiszkoptu> RodzajBiszkoptu { get; set; }
        public virtual DbSet<RodzajKremu> RodzajKremu { get; set; }
        public virtual DbSet<RodzajKsztaltu> RodzajKsztaltu { get; set; }
        public virtual DbSet<RodzajRozmiaru> RodzajRozmiaru { get; set; }
        public virtual DbSet<RodzajTortu> RodzajTortu { get; set; }
        public virtual DbSet<Rozmiar> Rozmiar { get; set; }
        public virtual DbSet<Smak> SmakSet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Torty> Torty { get; set; }
        public virtual DbSet<TortZamowienie> TortZamowienie { get; set; }
        public virtual DbSet<Zamowienie> Zamowienie { get; set; }
    }
}
