//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlaudiaPoliwka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pietra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pietra()
        {
            this.Biszkopt = new HashSet<Biszkopt>();
        }
    
        public long idPietra { get; set; }
        public Nullable<long> idSmak { get; set; }
        public Nullable<int> NrPietra { get; set; }
        public Nullable<long> idRodzajBiszkopt { get; set; }
        public Nullable<long> idRodzajKsztaltu { get; set; }
        public Nullable<long> idRodzajRozmiaru { get; set; }
        public string Dodatki { get; set; }
        public string Uwaga { get; set; }
        public Nullable<long> idRodzajKremu { get; set; }
        public Nullable<long> idTorty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biszkopt> Biszkopt { get; set; }
        public virtual RodzajKremu RodzajKremu { get; set; }
        public virtual RodzajKsztaltu RodzajKsztaltu { get; set; }
        public virtual RodzajRozmiaru RodzajRozmiaru { get; set; }
    }
}
