//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlaudiaPoliwka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platnosc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platnosc()
        {
            this.Zamowienie = new HashSet<Zamowienie>();
        }
    
        public long idPlatnosc { get; set; }
        public Nullable<decimal> KosztTotal { get; set; }
        public Nullable<decimal> Zaliczka { get; set; }
        public Nullable<bool> PotwierdzenieZaliczki { get; set; }
        public Nullable<long> idFormaZaliczki { get; set; }
        public Nullable<long> idFormaPlatnosci { get; set; }
    
        public virtual FormaPlatnosci FormaPlatnosci { get; set; }
        public virtual FormaZaliczki FormaZaliczki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie> Zamowienie { get; set; }
    }
}
