//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlaudiaPoliwka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Torty()
        {
            this.TortZamowienie = new HashSet<TortZamowienie>();
        }
    
        public Nullable<long> idRodzajTortu { get; set; }
        public long idTorty { get; set; }
        public bool GotowoscTortu { get; set; }
        public Nullable<long> idStylTortu { get; set; }
        public string NapisNa { get; set; }
        public string Zdjecie { get; set; }
        public Nullable<long> idPietra { get; set; }
    
        public virtual NazwaStylu NazwaStylu { get; set; }
        public virtual RodzajTortu RodzajTortu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TortZamowienie> TortZamowienie { get; set; }
    }
}
