//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlaudiaPoliwka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienie()
        {
            this.TortZamowienie = new HashSet<TortZamowienie>();
        }
    
        public string idUser { get; set; }
        public long idZamowienie { get; set; }
        public bool PotwOdbioru { get; set; }
        public bool ZlecenieRozliczenie { get; set; }
        public string Uwagi { get; set; }
        public bool PracPrzyjZam { get; set; }
        public Nullable<long> idDostawa { get; set; }
        public Nullable<long> idKlient { get; set; }
        public bool PracWykonalZam { get; set; }
        public bool PracWydalZam { get; set; }
        public Nullable<long> idDostawaDoPkt { get; set; }
        public Nullable<long> idPlatnosci { get; set; }
        public Nullable<long> idDostawaDoKlienta { get; set; }
        public Nullable<System.DateTime> DataOdbioru { get; set; }
        public Nullable<System.DateTime> DataZamowienia { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Dostawa Dostawa { get; set; }
        public virtual DostawaDoKlienta DostawaDoKlienta { get; set; }
        public virtual DostawaDoPkt DostawaDoPkt { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Platnosc Platnosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TortZamowienie> TortZamowienie { get; set; }
    }
}
